### PR TITLE
[WIP]Add initial contribution guidelines

### PR DESCRIPTION
**Pull request by CRF8-bixal**

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
The documentation looks good, I will go in and add my changes on this branch as well.

Are the config changes intended? Looks like there is a bunch of yml at the end of this.

**Comment by ivonne-gov** [comment]
@rich-allen-gov I didn't see those files! I think that's part of a pull that I did from 1.x-dev branch

**Comment by ivonne-gov** [comment]
@rich-allen-gov I changed the base of the PR to 1.x-base instead. =)

**Review by ghost — APPROVED** [review]
looks good. I will merge this in and create the testing instructions shortly

**Pull request merged**
