### PR TITLE
MB-4344 | Forwarding Nginx logs to Docker log collector

### PR DESCRIPTION
**Pull request by esacteksab**
Based on these docs https://github.com/nginxinc/docker-nginx/blob/master/stable/alpine/Dockerfile#L104-L106

I think this will do the thing.

### CODE REVIEW

**Comment by dynamike** [comment]
Doesn't look like it's working. The only logs I see coming from supervisor.
```
2020-10-29 16:30:11,302 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2020-10-29 16:30:11,302 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2020-10-29 16:30:11,303 INFO supervisord started with pid 1
2020-10-29 16:30:11,303 INFO supervisord started with pid 1
2020-10-29 16:30:12,305 INFO spawned: 'php-fpm' with pid 8
2020-10-29 16:30:12,305 INFO spawned: 'php-fpm' with pid 8
2020-10-29 16:30:12,308 INFO spawned: 'nginx' with pid 9
2020-10-29 16:30:12,308 INFO spawned: 'nginx' with pid 9
2020-10-29 16:30:13,518 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-10-29 16:30:13,518 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-10-29 16:30:13,518 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-10-29 16:30:13,518 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[ec2-user@ip-172-31-92-97 ~]$ sudo docker logs c4284d881a28
2020-10-29 16:30:11,302 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2020-10-29 16:30:11,302 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2020-10-29 16:30:11,303 INFO supervisord started with pid 1
2020-10-29 16:30:11,303 INFO supervisord started with pid 1
2020-10-29 16:30:12,305 INFO spawned: 'php-fpm' with pid 8
2020-10-29 16:30:12,305 INFO spawned: 'php-fpm' with pid 8
2020-10-29 16:30:12,308 INFO spawned: 'nginx' with pid 9
2020-10-29 16:30:12,308 INFO spawned: 'nginx' with pid 9
2020-10-29 16:30:13,518 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-10-29 16:30:13,518 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-10-29 16:30:13,518 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-10-29 16:30:13,518 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by esacteksab** [comment]
I wonder if this should be `/var/log/nginx/` instead https://github.com/transcom/move.mil/blob/1bf6e814981ee5aa8badceaffd45346729c36a3b/Dockerrun.aws.json#L14 ?

**Comment by esacteksab** [comment]
Looking at the docs here https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/single-container-docker-configuration.html

There is a sample `Dockerrun.aws.json` 

```json
{
  "AWSEBDockerrunVersion": "1",
  "Image": {
    "Name": "janedoe/image",
    "Update": "true"
  },
  "Ports": [
    {
      "ContainerPort": "1234"
    }
  ],
  "Volumes": [
    {
      "HostDirectory": "/var/app/mydb",
      "ContainerDirectory": "/etc/mysql"
    }
  ],
  "Logging": "/var/log/nginx",
  "Entrypoint": "/app/bin/myapp",
  "Command": "--argument"
}
```

And the specific section 

```
Logging

    Specify the directory inside the container to which your application writes logs. 
Elastic Beanstalk uploads any logs in this directory to Amazon S3 when you request tail or bundle logs. 
If you rotate logs to a folder named rotated within this directory, you can also configure Elastic Beanstalk to upload rotated logs to Amazon S3 for permanent storage. 
For more information, see Viewing logs from Amazon EC2 instances in your Elastic Beanstalk environment.
```

**Comment by esacteksab** [comment]
And I guess this https://github.com/transcom/move.mil/blob/1bf6e814981ee5aa8badceaffd45346729c36a3b/docker/supervisord.conf#L3 is why stupidvisord logs are show up.

**Comment by esacteksab** [comment]
`/var/log/nginx` in Dockerrun.aws.json seems to have done the trick!

```text
172.31.40.222 - - [18/Nov/2020:14:36:20 +0000] "GET / HTTP/1.1" 200 7704 "-" "ELB-HealthChecker/2.0"
172.31.15.103 - - [18/Nov/2020:14:36:20 +0000] "GET / HTTP/1.1" 200 7704 "-" "ELB-HealthChecker/2.0"
172.31.40.222 - - [18/Nov/2020:14:36:32 +0000] "GET /sites/default/files/css/css_MthEtQV3mOlrZTjUT0nELJE6fpdjpKLM00JHkGrUb50.css HTTP/1.1" 200 2758 "http://movemil-stg.us-east-1.elasticbeanstalk.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0"
172.31.40.222 - - [18/Nov/2020:14:36:32 +0000] "GET /sites/default/files/css/css_sUlBjurMjkZ3ACR1MHGq4nQtDz5tlyvytFrnSwFIWX4.css HTTP/1.1" 200 21607 "http://movemil-stg.us-east-1.elasticbeanstalk.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0"
172.31.40.222 - - [18/Nov/2020:14:36:32 +0000] "GET /themes/custom/move_mil/assets/img/icon-dot-gov.svg HTTP/1.1" 200 389 "http://movemil-stg.us-east-1.elasticbeanstalk.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0"
172.31.40.222 - - [18/Nov/2020:14:36:32 +0000] "GET /themes/custom/move_mil/assets/img/close.svg HTTP/1.1" 200 778 "http://movemil-stg.us-east-1.elasticbeanstalk.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0"
172.31.40.222 - - [18/Nov/2020:14:36:32 +0000] "GET /sites/default/files/2018-06/scheduleyourmove.png HTTP/1.1" 200 31094 "http://movemil-stg.us-east-1.elasticbeanstalk.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0"
172.31.40.222 - - [18/Nov/2020:14:36:32 +0000] "GET /sites/default/files/2018-04/getready.png HTTP/1.1" 200 5365 "http://movemil-stg.us-east-1.elasticbeanstalk.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0"
172.31.40.222 - - [18/Nov/2020:14:36:32 +0000] "GET /sites/default/files/2018-04/movingtruckhero.jpg HTTP/1.1" 200 207284 "http://movemil-stg.us-east-1.elasticbeanstalk.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0"
```

**Review by dynamike — APPROVED** [review]
looks good!

**Pull request merged**
